name: Package and Publish Extension

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    environment: marketplace
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install VSCE
      run: npm install -g @vscode/vsce@latest
      
    - name: Generate AST docs (AstDoc.json)
      shell: pwsh
      working-directory: ${{ github.workspace }}
      run: ./GenerateAstDocs.ps1

    - name: Compile extension
      run: npm run compile
      
    - name: Package extension
      run: vsce package
      
    - name: Upload package artifact
      uses: actions/upload-artifact@v4
      with:
        name: extension-package
        path: '*.vsix'
        retention-days: 30
        
    - name: Publish to VS Code Marketplace
      if: github.event_name == 'release'
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
      run: vsce publish --pat $VSCE_PAT